-- LearnFlow: private cloud workspace for every signed-in user
-- Run this ONCE in Supabase SQL Editor.

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  code text not null,
  title text not null,
  instructor text not null default '',
  icon text not null default '•',
  color text not null default '#7563e9',
  soft text not null default '#e9e5ff',
  progress integer not null default 0 check (progress between 0 and 100),
  next_item text not null default 'Add your first lesson',
  meeting text not null default 'Schedule not set',
  created_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  course_id bigint references public.courses(id) on delete set null,
  course_code text not null default 'Personal',
  due text not null default 'Tomorrow',
  time text not null default '5:00 PM',
  priority text not null default 'Medium' check (priority in ('Low','Medium','High')),
  done boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text not null,
  category text not null default 'Personal',
  created_at timestamptz not null default now()
);

alter table public.courses enable row level security;
alter table public.tasks enable row level security;
alter table public.notes enable row level security;

drop policy if exists "courses_select_own" on public.courses;
drop policy if exists "courses_insert_own" on public.courses;
drop policy if exists "courses_update_own" on public.courses;
drop policy if exists "courses_delete_own" on public.courses;
create policy "courses_select_own" on public.courses for select to authenticated using ((select auth.uid()) = user_id);
create policy "courses_insert_own" on public.courses for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "courses_update_own" on public.courses for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "courses_delete_own" on public.courses for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "tasks_select_own" on public.tasks;
drop policy if exists "tasks_insert_own" on public.tasks;
drop policy if exists "tasks_update_own" on public.tasks;
drop policy if exists "tasks_delete_own" on public.tasks;
create policy "tasks_select_own" on public.tasks for select to authenticated using ((select auth.uid()) = user_id);
create policy "tasks_insert_own" on public.tasks for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "tasks_update_own" on public.tasks for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "tasks_delete_own" on public.tasks for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "notes_select_own" on public.notes;
drop policy if exists "notes_insert_own" on public.notes;
drop policy if exists "notes_update_own" on public.notes;
drop policy if exists "notes_delete_own" on public.notes;
create policy "notes_select_own" on public.notes for select to authenticated using ((select auth.uid()) = user_id);
create policy "notes_insert_own" on public.notes for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "notes_update_own" on public.notes for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "notes_delete_own" on public.notes for delete to authenticated using ((select auth.uid()) = user_id);

create index if not exists courses_user_id_idx on public.courses(user_id);
create index if not exists tasks_user_id_idx on public.tasks(user_id);
create index if not exists notes_user_id_idx on public.notes(user_id);
